# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelShow(object):
    def setupUi(self, LabelShow):
        LabelShow.setObjectName("LabelShow")
        LabelShow.resize(260, 216)
        LabelShow.setStyleSheet("QWidget{\n"
"background: #2c344b;\n"
"}\n"
"QLabel{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-weight: 400;\n"
"text-align: left;\n"
"color: #8e9fc4;\n"
"}\n"
"/*QWidget{\n"
"background:#2c344b\n"
"}*/\n"
"/*整体尺寸*/\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #4A90E8;\n"
"background: #4A90E8;\n"
"height: 5px;\n"
"border-radius: 3px;\n"
"padding-left:-1px;\n"
"padding-right:-1px;\n"
"}\n"
"/*滑过的颜色*/\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #5DCCFF, stop: 1 #1874CD);\n"
"border: 1px solid #4A708B;\n"
"height: 10px;\n"
"border-radius: 2px;\n"
"}\n"
"/*未滑过的颜色*/\n"
"QSlider::add-page:horizontal {\n"
"background: #141A2B;\n"
"border: 0px solid #777;\n"
"height: 10px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"/*滑块形状颜色*/\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, \n"
"    stop:0.6 rgba(255, 255, 255, 255), stop:0.778409 #45ADED);\n"
"\n"
"    width: 11px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.6 #2A8BDA, \n"
"    stop:0.778409 rgba(255, 255, 255, 255));\n"
"\n"
"    width: 11px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #00009C;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(LabelShow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetOfAnnotationDisplay = QtWidgets.QWidget(LabelShow)
        self.widgetOfAnnotationDisplay.setStyleSheet("")
        self.widgetOfAnnotationDisplay.setObjectName("widgetOfAnnotationDisplay")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetOfAnnotationDisplay)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetTranparency = QtWidgets.QWidget(self.widgetOfAnnotationDisplay)
        self.widgetTranparency.setStyleSheet("width:342px;\n"
"height:40px;")
        self.widgetTranparency.setObjectName("widgetTranparency")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widgetTranparency)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelTransparencyTip = QtWidgets.QLabel(self.widgetTranparency)
        self.labelTransparencyTip.setStyleSheet("")
        self.labelTransparencyTip.setObjectName("labelTransparencyTip")
        self.horizontalLayout_7.addWidget(self.labelTransparencyTip)
        spacerItem = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.sliderTransparency = QtWidgets.QSlider(self.widgetTranparency)
        self.sliderTransparency.setStyleSheet("width: 161px;\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"background: #141a2b;\n"
"")
        self.sliderTransparency.setMinimum(1)
        self.sliderTransparency.setMaximum(100)
        self.sliderTransparency.setProperty("value", 50)
        self.sliderTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTransparency.setObjectName("sliderTransparency")
        self.horizontalLayout_7.addWidget(self.sliderTransparency)
        self.verticalLayout_2.addWidget(self.widgetTranparency)
        self.widgetSelcetedTransparency = QtWidgets.QWidget(self.widgetOfAnnotationDisplay)
        self.widgetSelcetedTransparency.setStyleSheet("width:342px;\n"
"height:40px;")
        self.widgetSelcetedTransparency.setObjectName("widgetSelcetedTransparency")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widgetSelcetedTransparency)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelSelectedTransparencyTip = QtWidgets.QLabel(self.widgetSelcetedTransparency)
        self.labelSelectedTransparencyTip.setStyleSheet("")
        self.labelSelectedTransparencyTip.setObjectName("labelSelectedTransparencyTip")
        self.horizontalLayout_5.addWidget(self.labelSelectedTransparencyTip)
        spacerItem1 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.sliderSelectedTransparency = QtWidgets.QSlider(self.widgetSelcetedTransparency)
        self.sliderSelectedTransparency.setStyleSheet("width: 161px;\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"background: #141a2b;\n"
"")
        self.sliderSelectedTransparency.setMinimum(1)
        self.sliderSelectedTransparency.setMaximum(100)
        self.sliderSelectedTransparency.setProperty("value", 50)
        self.sliderSelectedTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSelectedTransparency.setObjectName("sliderSelectedTransparency")
        self.horizontalLayout_5.addWidget(self.sliderSelectedTransparency)
        self.verticalLayout_2.addWidget(self.widgetSelcetedTransparency)
        self.widgetInstanceColor = QtWidgets.QWidget(self.widgetOfAnnotationDisplay)
        self.widgetInstanceColor.setEnabled(False)
        self.widgetInstanceColor.setObjectName("widgetInstanceColor")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widgetInstanceColor)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelInstanceColor = QtWidgets.QLabel(self.widgetInstanceColor)
        self.labelInstanceColor.setStyleSheet("")
        self.labelInstanceColor.setObjectName("labelInstanceColor")
        self.horizontalLayout_6.addWidget(self.labelInstanceColor)
        self.comboBoxInstanceColor = QtWidgets.QComboBox(self.widgetInstanceColor)
        self.comboBoxInstanceColor.setStyleSheet("font-family: \"Microsoft YaHei\";\n"
"font-weight: 400;\n"
"text-align: left;\n"
"color: #8e9fc4;")
        self.comboBoxInstanceColor.setEditable(True)
        self.comboBoxInstanceColor.setObjectName("comboBoxInstanceColor")
        self.comboBoxInstanceColor.addItem("")
        self.comboBoxInstanceColor.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxInstanceColor)
        self.verticalLayout_2.addWidget(self.widgetInstanceColor)
        self.widgetApplyAnnotationDisplay = QtWidgets.QWidget(self.widgetOfAnnotationDisplay)
        self.widgetApplyAnnotationDisplay.setStyleSheet("\n"
"height:40px;")
        self.widgetApplyAnnotationDisplay.setObjectName("widgetApplyAnnotationDisplay")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetApplyAnnotationDisplay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pBtnApplyAnnotationDislay = QtWidgets.QPushButton(self.widgetApplyAnnotationDisplay)
        self.pBtnApplyAnnotationDislay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBtnApplyAnnotationDislay.setStyleSheet("width: 70px;\n"
"height: 30px;\n"
"background: #4a90e8;\n"
"font-family: \"Microsoft YaHei\";\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"color: #ebf6ff;\n"
"border-radius:5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/确定.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnApplyAnnotationDislay.setIcon(icon)
        self.pBtnApplyAnnotationDislay.setObjectName("pBtnApplyAnnotationDislay")
        self.horizontalLayout.addWidget(self.pBtnApplyAnnotationDislay)
        spacerItem3 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widgetApplyAnnotationDisplay)
        self.verticalLayout.addWidget(self.widgetOfAnnotationDisplay)

        self.retranslateUi(LabelShow)
        QtCore.QMetaObject.connectSlotsByName(LabelShow)

    def retranslateUi(self, LabelShow):
        _translate = QtCore.QCoreApplication.translate
        LabelShow.setWindowTitle(_translate("LabelShow", "Form"))
        self.labelTransparencyTip.setText(_translate("LabelShow", "透明度："))
        self.labelSelectedTransparencyTip.setText(_translate("LabelShow", "选中透明度："))
        self.labelInstanceColor.setText(_translate("LabelShow", "实例颜色："))
        self.comboBoxInstanceColor.setItemText(0, _translate("LabelShow", "与类型一致"))
        self.comboBoxInstanceColor.setItemText(1, _translate("LabelShow", "随机设置"))
        self.pBtnApplyAnnotationDislay.setText(_translate("LabelShow", "应用"))
#import resources_rc
