# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Morphology.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Morphology(object):
    def setupUi(self, Morphology):
        Morphology.setObjectName("Morphology")
        Morphology.resize(274, 216)
        Morphology.setStyleSheet("QWidget{\n"
"background: #2c344b;\n"
"}\n"
"QLabel{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-weight: 400;\n"
"text-align: left;\n"
"color: #8e9fc4;\n"
"}\n"
"/*QWidget{\n"
"background:#2c344b\n"
"}*/\n"
"/*整体尺寸*/\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #4A90E8;\n"
"background: #4A90E8;\n"
"height: 5px;\n"
"border-radius: 3px;\n"
"padding-left:-1px;\n"
"padding-right:-1px;\n"
"}\n"
"/*滑过的颜色*/\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #5DCCFF, stop: 1 #1874CD);\n"
"border: 1px solid #4A708B;\n"
"height: 10px;\n"
"border-radius: 2px;\n"
"}\n"
"/*未滑过的颜色*/\n"
"QSlider::add-page:horizontal {\n"
"background: #141A2B;\n"
"border: 0px solid #777;\n"
"height: 10px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"/*滑块形状颜色*/\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, \n"
"    stop:0.6 rgba(255, 255, 255, 255), stop:0.778409 #45ADED);\n"
"\n"
"    width: 11px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.6 #2A8BDA, \n"
"    stop:0.778409 rgba(255, 255, 255, 255));\n"
"\n"
"    width: 11px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #00009C;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Morphology)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetOfMorphologicalTrans = QtWidgets.QWidget(Morphology)
        self.widgetOfMorphologicalTrans.setStyleSheet("")
        self.widgetOfMorphologicalTrans.setObjectName("widgetOfMorphologicalTrans")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetOfMorphologicalTrans)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetTargetType = QtWidgets.QWidget(self.widgetOfMorphologicalTrans)
        self.widgetTargetType.setEnabled(False)
        self.widgetTargetType.setObjectName("widgetTargetType")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetTargetType)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTargetType = QtWidgets.QLabel(self.widgetTargetType)
        self.labelTargetType.setStyleSheet("")
        self.labelTargetType.setObjectName("labelTargetType")
        self.horizontalLayout.addWidget(self.labelTargetType)
        self.comboBoxTargetType = QtWidgets.QComboBox(self.widgetTargetType)
        self.comboBoxTargetType.setStyleSheet("font-family: \"Microsoft YaHei\";\n"
"font-weight: 400;\n"
"text-align: left;\n"
"color: #8e9fc4;")
        self.comboBoxTargetType.setEditable(True)
        self.comboBoxTargetType.setObjectName("comboBoxTargetType")
        self.comboBoxTargetType.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxTargetType)
        self.verticalLayout_2.addWidget(self.widgetTargetType)
        self.widgetOperationType = QtWidgets.QWidget(self.widgetOfMorphologicalTrans)
        self.widgetOperationType.setEnabled(False)
        self.widgetOperationType.setObjectName("widgetOperationType")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widgetOperationType)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelOperationType = QtWidgets.QLabel(self.widgetOperationType)
        self.labelOperationType.setStyleSheet("")
        self.labelOperationType.setObjectName("labelOperationType")
        self.horizontalLayout_10.addWidget(self.labelOperationType)
        self.comboBoxOperationType = QtWidgets.QComboBox(self.widgetOperationType)
        self.comboBoxOperationType.setStyleSheet("color: #8e9fc4;")
        self.comboBoxOperationType.setEditable(True)
        self.comboBoxOperationType.setObjectName("comboBoxOperationType")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.comboBoxOperationType.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBoxOperationType)
        self.verticalLayout_2.addWidget(self.widgetOperationType)
        self.widgetParameterName = QtWidgets.QWidget(self.widgetOfMorphologicalTrans)
        self.widgetParameterName.setStyleSheet("width:342px;\n"
"height:40px;")
        self.widgetParameterName.setObjectName("widgetParameterName")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widgetParameterName)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelParameterName = QtWidgets.QLabel(self.widgetParameterName)
        self.labelParameterName.setStyleSheet("")
        self.labelParameterName.setObjectName("labelParameterName")
        self.horizontalLayout_11.addWidget(self.labelParameterName)
        self.labelParameterNameMin = QtWidgets.QLabel(self.widgetParameterName)
        self.labelParameterNameMin.setStyleSheet("")
        self.labelParameterNameMin.setObjectName("labelParameterNameMin")
        self.horizontalLayout_11.addWidget(self.labelParameterNameMin)
        self.sliderParameterName = QtWidgets.QSlider(self.widgetParameterName)
        self.sliderParameterName.setStyleSheet("width: 161px;\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"background: #141a2b;\n"
"")
        self.sliderParameterName.setMinimum(1)
        self.sliderParameterName.setMaximum(10)
        self.sliderParameterName.setProperty("value", 1)
        self.sliderParameterName.setOrientation(QtCore.Qt.Horizontal)
        self.sliderParameterName.setObjectName("sliderParameterName")
        self.horizontalLayout_11.addWidget(self.sliderParameterName)
        self.labelParameterNameMax = QtWidgets.QLabel(self.widgetParameterName)
        self.labelParameterNameMax.setStyleSheet("")
        self.labelParameterNameMax.setObjectName("labelParameterNameMax")
        self.horizontalLayout_11.addWidget(self.labelParameterNameMax)
        spacerItem = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widgetParameterName)
        self.widgetApplayMorphological = QtWidgets.QWidget(self.widgetOfMorphologicalTrans)
        self.widgetApplayMorphological.setStyleSheet("\n"
"height:40px;")
        self.widgetApplayMorphological.setObjectName("widgetApplayMorphological")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widgetApplayMorphological)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem1 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.pBtnApplyMorphological = QtWidgets.QPushButton(self.widgetApplayMorphological)
        self.pBtnApplyMorphological.setEnabled(True)
        self.pBtnApplyMorphological.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBtnApplyMorphological.setStyleSheet("width: 70px;\n"
"height: 30px;\n"
"background: #4a90e8;\n"
"font-family: \"Microsoft YaHei\";\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"color: #ebf6ff;\n"
"border-radius:5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/确定.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtnApplyMorphological.setIcon(icon)
        self.pBtnApplyMorphological.setObjectName("pBtnApplyMorphological")
        self.horizontalLayout_15.addWidget(self.pBtnApplyMorphological)
        spacerItem2 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widgetApplayMorphological)
        self.verticalLayout.addWidget(self.widgetOfMorphologicalTrans)

        self.retranslateUi(Morphology)
        QtCore.QMetaObject.connectSlotsByName(Morphology)

    def retranslateUi(self, Morphology):
        _translate = QtCore.QCoreApplication.translate
        Morphology.setWindowTitle(_translate("Morphology", "Form"))
        self.labelTargetType.setText(_translate("Morphology", "目标类型："))
        self.comboBoxTargetType.setItemText(0, _translate("Morphology", "XXX"))
        self.labelOperationType.setText(_translate("Morphology", "操作类型："))
        self.comboBoxOperationType.setItemText(0, _translate("Morphology", "无"))
        self.comboBoxOperationType.setItemText(1, _translate("Morphology", "膨胀"))
        self.comboBoxOperationType.setItemText(2, _translate("Morphology", "腐蚀"))
        self.comboBoxOperationType.setItemText(3, _translate("Morphology", "开运算"))
        self.comboBoxOperationType.setItemText(4, _translate("Morphology", "闭运算"))
        self.comboBoxOperationType.setItemText(5, _translate("Morphology", "小区域删除"))
        self.comboBoxOperationType.setItemText(6, _translate("Morphology", "骨架化"))
        self.comboBoxOperationType.setItemText(7, _translate("Morphology", "去枝杈"))
        self.labelParameterName.setText(_translate("Morphology", "参数名："))
        self.labelParameterNameMin.setText(_translate("Morphology", "1"))
        self.labelParameterNameMax.setText(_translate("Morphology", "10"))
        self.pBtnApplyMorphological.setText(_translate("Morphology", "应用"))
#import resources_rc
